name: Github Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Output triggered event and branch name
        run: |
          echo "The job was triggered by event: ${{ github.event_name }}"
          echo "The name of the branch is: ${{ github.ref }}"
          
      - uses: actions/checkout@v2
      
      - name: List files
        run: |
          echo "The repository is ${{ github.repository }}"
